version: '3'

services:
    database_api:
        build: ./database_api_service
        image: 127.0.0.1:5050/database_api:database_api
        ports:
            - "5000:5000"
        depends_on:
            - database_primary
            - images
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==worker"
        networks:
            - database
        environment:
            - DATABASE_URL=mongodb://root:owl45#21@database_primary,database_secondary/?replicaSet=replicaset
            - DATABASE_PORT=27017 

    database_primary:
        image: 'bitnami/mongodb:4'
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=database_primary
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_REPLICA_SET_KEY=replicasetkey
            - MONGODB_ROOT_PASSWORD=owl45#21    
        volumes:
            - 'database:/bitnami'
        networks:
            - database
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==manager"

    database_secondary:
        image: 'bitnami/mongodb:4'
        depends_on:
            - database_primary
        environment:
            - MONGODB_REPLICA_SET_MODE=secondary
            - MONGODB_PRIMARY_HOST=database_primary
            - MONGODB_PRIMARY_PORT_NUMBER=27017
            - MONGODB_REPLICA_SET_KEY=replicasetkey
            - MONGODB_PRIMARY_ROOT_PASSWORD=owl45#21
        networks:
            - database
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==worker"

    database_arbiter:
        image: 'bitnami/mongodb:4'
        depends_on:
         - database_primary
        environment:
            - MONGODB_REPLICA_SET_MODE=arbiter
            - MONGODB_PRIMARY_HOST=database_primary
            - MONGODB_PRIMARY_PORT_NUMBER=27017
            - MONGODB_REPLICA_SET_KEY=replicasetkey
            - MONGODB_PRIMARY_ROOT_PASSWORD=owl45#21
        networks:
            - database
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==worker"

    images:
        image: registry:2
        ports:
            - "5050:5000"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==manager"
        networks:
            - database
        volumes:
            - images:/var/lib/registry

    visualizer:
        image: dockersamples/visualizer
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
        - "8080:8080"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==manager"

networks:
    database:

volumes:
    images:
    database: